### ISSUE TITLE
EEPROMs.md doesn't seem to be linked to from anywhere

### ISSUE THREAD

**Issue by SpenceKonde** [espruino/EspruinoDocs#113]
I'm not sure why mosfets.md shows up in the devices list on the webside, but EEPROMs.md doesn't. 

You can access it at http://www.espruino.com/EEPROMs but there's no link at http://www.espruino.com/Tutorials or http://www.espruino.com/Modules so it's unlikely anyone will ever see it.

**Comment by gfwilliams** [comment]
Where it's filed depends on what directory it's in as well as the keywords. The directory is just added as another keyword.

I found out the problem though. It had a space at the top, so it was under 'Devices' in http://www.espruino.com/Tutorials but way just blank!
