### ISSUE TITLE
ESP8266 getIP() returns incorrect result

### ISSUE THREAD

**Issue by SpenceKonde** [espruino/EspruinoDocs#127]
I'm getting 192.168.4.1 as the IP when I do wifi.getIP(). 

The IP address that the ESP8266 actually gets is 192.168.2.102 (in my case). It seems that it's getting the IP that it would use when acting as an access point, rather than the IP it has as a client. If possible, the ESP8266WiFi module should return the appropriate IP address for the mode the ESP8266 is currently operating in.

**Comment by gfwilliams** [comment]
Hmm. Are you using the same esp8266 firmware? I remember looking at this
and was pretty sure it worked. The at command returns 2 IPs when the ap
mode is 3, but was pretty sure it just returned a single one if the mode
was 1 or 2 (which is all the driver should set it to).

- Gordon

**Comment by SpenceKonde** [comment]
This was with f/w version 0018000902-AI03, using the example code...

**Comment by gfwilliams** [comment]
Thanks - found a bit of a copy/paste bug :)
