### ISSUE TITLE
ESP8266 needs error handling. 

### ISSUE THREAD

**Issue by SpenceKonde** [espruino/EspruinoDocs#131]
Sometimes, the ESP8266 will refuse to respond to AT+RST, particularly immediately after power-on. 

In this case, we should wait a short time, and try again. 

Additionally, after a failure like what I was experiencing on the forums, it might make sense for the Espruino to wait a second, then do AT+RST, and then fire a callback to that gets the ESP8266 back into it's old state (maybe just the initial setup callback? ) to try to get it working again.

**Comment by gfwilliams** [comment]
Closing this, as we do fail with an error if reset times out now - it's pretty easy to either re-reset or handle it in some other way in code
