### ISSUE TITLE
Create tern-espruino project

### ISSUE THREAD

**Issue by angelozerr** [espruino/EspruinoDocs#133]
It shoud be cool if you could create a new project called tern-espruino which hosts https://github.com/espruino/EspruinoDocs/blob/master/bin/espruino.json and package.json.

It will give yoiu the capability to publish your tern plugin with npm and users will abel to install it with npm.

Thanks!

**Comment by gfwilliams** [comment]
Closing this - realistically I don't think it's going to get done, and the up to date espruino.json file can easily be downloaded from http://www.espruino.com/json/espruino.json
