### ISSUE TITLE
ESP8266 module doesn't work with multiple connections

### ISSUE THREAD

**Issue by SpenceKonde** [espruino/EspruinoDocs#138]
If it tries, everything goes to hell, because the handlers (ie for "Unlink"/etc) don't have any provision for determining which socket they are associated with.

**Comment by gfwilliams** [comment]
Yes, it's particularly bad design.

I wondered whether it was possible to just assume that the socket that data was last received on was the one that should be closed. Or maybe there's some kind of 'socket status' command that could be used to check which one had actually closed.

**Comment by gfwilliams** [comment]
Should be fixed now - at least when using the newer ESP8266 firmware.
