### ISSUE TITLE
tasks/File Converter.md allows files to be larger then 20KiB

### ISSUE THREAD

**Issue by joppiesaus** [espruino/EspruinoDocs#141]
Today I wanted to convert a large file, but of course that didn't work because it was simply to large.
The console had thrown me a `Uncaught RangeError: Maximum call stack size exceeded`. The file was larger then 20KiB and it didn't leave the "File too long - must be less than 20kB".
That's because it still executes `var b64Str = 'atob("'+btoa(String.fromCharCode.apply(null, bytes))+'")';`, when this is too large js will just crash.
I'll make a pull request that fixes this.

**Comment by gfwilliams** [comment]
Argh, Thanks!

Actually I should try and improve that code anyway - just made a bug for it: https://github.com/espruino/EspruinoDocs/issues/144

Thanks for the fix!

**Comment by gfwilliams** [comment]
Actually, could you post up your code? I'm surprised you got the call stack error... Usually it'd just be a normal 'out of memory'...

**Comment by joppiesaus** [comment]
@gfwilliams :+1: 
I'm not sure what you mean, but I got the Uncaught RangeError at the `var b64Str = 'atob("'+btoa(String.fromCharCode.apply(null, bytes))+'")';`
(https://raw.githubusercontent.com/espruino/EspruinoDocs/3ca286496c2ea12214223b0b5cc6efaa91c96df9/tasks/File%20Converter.md)[in FileConverter.md line 59

**Comment by gfwilliams** [comment]
Oh, ok - it was actually an error on your PC rather than in Espruino? :)

**Comment by joppiesaus** [comment]
Affirmative
