### ISSUE TITLE
tasks/File IO.md

### ISSUE THREAD

**Issue by stephaneAG** [espruino/EspruinoDocs#183]
Hi there Gordon !

I was reading the FIle IO page, & although it seems obvious,beginners may not understand where the problem is ( though, they should, or programming 'll be hard for them .. )

the glitch is the following: "for var i in arr" should be, I think, "for var i in files"

concerned section:
```
Read directory contents

var files = require("fs").readdirSync();
for (var i in arr) // ERROR: should be "for (var i in files)"
  console.log("Found file "+files[i]);
```

**Comment by gfwilliams** [comment]
Thanks! If you spot any more issues like this, please let me know!

The website will update this week hopefully
