### ISSUE TITLE
boards/EspruinoESP8266.md

### ISSUE THREAD

**Issue by wilberforce** [espruino/EspruinoDocs#201]
WIFI

The ESP8266 can only support a finite number of concurrent TCP/IP connections when performing the role of an access point. The Espruino implementation is configured to constrain this to 10.

I believe the current setting is 4 rather than 10

**Comment by gfwilliams** [comment]
I don't see this mentioned any more. Has it been revised already?

**Comment by wilberforce** [comment]
Hmm- not useful as I didn't reference where I saw this!
