### ISSUE TITLE
boards/Pico.md

### ISSUE THREAD

**Issue by snawolf** [espruino/EspruinoDocs#212]
I received my Espruino Pico v1.4 from Seed Studio.

I ran the Web IDE inside Chrome and updated the firmware to version 1v84. Besides the Chrome app, I used PuTTY, and both worked OK.

In the IDE tutorial, after entering the flash() function, and receiving the correct function added message, running the function only turns on the red LED. It doesn't flash.

When trying the Pico Buttons tutorial, most things worked, except that any function with digitalPulse fails. The two external buttons work OK, as when I changed the function to use digitalWrite instead of digitalPulse, the second external switch would light both LEDs 1 & 2.

Trying digitalPulse(LED1, 1, 500) on a command line would turn on a LED, but only that. It would never pulse.

In the FAQ, under "When I type a command, why does Espruino print '=undefined'?," your first example, >analogRead(D0), tries an analogRead to a digital pin (D0), giving an error message. How you ever got the result =0.0324 is a mystery.

 
The problems are digitalPulse not working properly, followed by the tutorial flash() not flashing, and the minor FAQ error.

A better email address for me is artbecker2001@yahoo.com

Thank you.

**Comment by gfwilliams** [comment]
Closing this, as this was [also asked on the forum](http://forum.espruino.com/conversations/280179/#comment12724483) - which is probably the better place. It's answered there.
