### ISSUE TITLE
devices/Bluetooth.md

### ISSUE THREAD

**Issue by afitterling** [espruino/EspruinoDocs#233]
I have a command interpreter for communication between two espruinos via the HC-05 I send you the code recently. May we add it?
https://github.com/afitterling/espruino

k r Alex

**Comment by gfwilliams** [comment]
Sorry for the crazily late reply to this,

Thanks! I think as an example (so a JS file in https://github.com/espruino/EspruinoDocs/tree/master/examples with a bit of explanation in a comment at the top) it might make a lot of sense?

**Comment by afitterling** [comment]
Hi, no prob. I have to admit, the code I posted is tight enough but needs refactorings. I also have to admit, I switched to particle (particle.io) devices already. So not sure, wether I find time to do this. warm regards, Alex

**Comment by afitterling** [comment]
(not because of the late reply, rather because to simply focus on iot products)
