### ISSUE TITLE
devices/CC3000.md

### ISSUE THREAD

**Issue by afitterling** [espruino/EspruinoDocs#234]
I have got the the CC3000 shield (for the arduino) I have successfully wired it up.
May we add it a picture of it?

kind regards.
Alex

**Comment by gfwilliams** [comment]
Hi - yes, absolutely - if you attach the picture here and give some information about wiring, I'll put it online. Otherwise you can make the changes your self and issue a pull request via GitHub if you want.

**Comment by gfwilliams** [comment]
No response - closing :(
