### ISSUE TITLE
How to `load()` after `reset()`?

### ISSUE THREAD

**Issue by ceremcem** [espruino/EspruinoDocs#240]
I need to reboot if some kind of heartbeat is overflowed, but `reset()` causes a reboot without app code `load()`ed. 

How can I simulate a power toggle with a command?

**Comment by gfwilliams** [comment]
Just type `load()` - that's what it does.

Please can you ask these questions [on the forum](http://forum.espruino.com/) - that's what it's for - this isn't really an issue,

**Comment by ceremcem** [comment]
We were expecting a `reboot()` or `restart()` like command. You may consider a section with these keywords in the documentation. 

Moreover, this might be considered as a (small) bug, since this is an expected command and we are unable to find it in the documentation. Interaction should not be required for such a small need, IMO

**Comment by trandi** [comment]
Really !? A bug because it's not what YOU expected and YOU could not find
it ???
On a project where Gordon (and others) has invested soooooo much time FOR
FREE ??!!

Dan

**Comment by gfwilliams** [comment]
Well, [the docs for reset](http://www.espruino.com/Reference#l__global_reset) do link to `load`, and the docs for `load` say:

> Espruino will resume from where it was when you last typed save().

Its seems relatively clear?

**Comment by gfwilliams** [comment]
I'll modify the docs for 'load' though to mention restart/reboot, in case someone searches for it.

**Comment by ceremcem** [comment]
Thank you. I've forked the documentation, I'll create pull requests for similar needs next time.
