### ISSUE TITLE
HTU21D.md: issue with degree symbol (°)

### ISSUE THREAD

**Issue by The-Alchemist** [espruino/EspruinoDocs#248]
I get a weird symbol after copy/pasting the code from http://www.espruino.com/HTU21D:

![image](https://cloud.githubusercontent.com/assets/812287/15452460/34f657e0-1fbd-11e6-9f0c-ce456b1af02d.png)

I copy/pasted from Chrome.  Anyone else see this problem?

**Comment by MaBecker** [comment]
This is not a module issue.

Typing direct to console works

````
t = 23;
=23
>console.log("t = " + t + " °C");
t = 23 °C
=undefined
> 
````

using upload it is printing more than °C 

````
t = 23;
console.log("t = " + t + " °C");

/* output

t = 23 Â°C
=undefined

*/
````

Plattform: Espruino version 1v85 on ESP8266

**Comment by gfwilliams** [comment]
It's actually a Web IDE issue (kind of) - I think the degree symbol is being treated as utf-8 unicode, so is actually being sent as 2 characters - and the Web IDE isn't decoding the received characters back into one character.

A quick fix would be to make the tutorial use the correct numeric ascii code for a degree symbol...

**Comment by The-Alchemist** [comment]
Thanks, guys!

@gfwilliams : If you point me in the right direction in the Web IDE code, I might be able to fix the issue.

**Comment by MaBecker** [comment]
Hi @The-Alchemist,

does it work for you too ?

![bildschirmfoto 2017-02-02 um 10 27 14](https://cloud.githubusercontent.com/assets/15932646/22543770/49485a42-e932-11e6-8789-85d41fc18956.JPG)

**Comment by gfwilliams** [comment]
Thanks for spotting this - I think this was fixed a month or so ago.

Sorry I missed the previous post, but FYI it's in `unicode.js` I think
