### ISSUE TITLE
boards/MicroBit.md BTN1 shown on wrong pin

### ISSUE THREAD

**Issue by veryalien** [espruino/EspruinoDocs#267]
BTN1 is on pin d5, not on pin d4 as shown on the Microbit edge connector pinout.

**Comment by veryalien** [comment]
It seems to be a problem with the Microbit edge connector itself, not with your diagram

**Comment by veryalien** [comment]
After checking and re-checking it is a problem: Espruino is consistently using the 'wrong' pin numbers. Unfortunately, the pin numbers don't match those given here [https://www.microbit.co.uk/device/pins] and the Microbit edge connector.

**Comment by gfwilliams** [comment]
Not sure I understand - D0/1/2/etc are all in the right place and work fine? I'm sure I've used them in the past?

Or are you using integers like `2` instead of `D2`?

**Comment by gfwilliams** [comment]
Oh right. you opened a new bug as well: https://github.com/espruino/Espruino/issues/896

**Comment by gfwilliams** [comment]
This'll be fixed automatically on the next website update now.
