### ISSUE TITLE
Websocket client needs masking

### ISSUE THREAD

**Issue by gfwilliams** [espruino/EspruinoDocs#268]
`ws` on node.hs is fine with it, but vertx.io drops connections if it's not there:

http://forum.espruino.com/conversations/291544/#comment13167995

The code that needs changing is in `send`, in: https://github.com/espruino/EspruinoDocs/blob/master/modules/ws.js#L175

There is already some unmasking code, so you're basically just doing the same thing again: https://github.com/espruino/EspruinoDocs/blob/master/modules/ws.js#L154

**Comment by injecteer** [comment]
I fixed the masking issue.
Now it's active by default and can be deactivated via the `masking` option.

I also fixed the ping sending. The interval-timer is cleared, if the websocket is disconnected.

[ws.zip](https://github.com/espruino/EspruinoDocs/files/430512/ws.zip)

**Comment by gfwilliams** [comment]
Thanks! I've just updated - hope that works for you!

**Comment by injecteer** [comment]
I tested that for sending and receiving, and it's working like charm. Thanks!
