### ISSUE TITLE
Console CLI

### ISSUE THREAD

**Issue by xavierzwirtz** [espruino/EspruinoDocs#28]
I have created a console interface, node library, and grunt task to make interacting with the espruino from a normal file system very easy. Would you have any issue with me adding them to the docs?

[CLI and Node.js library](https://bitbucket.org/VoiceOfWisdom/node-espruino)
[Grunt task.](https://bitbucket.org/VoiceOfWisdom/grunt-espruino)

**Comment by gfwilliams** [comment]
Closing this now... There's also https://github.com/espruino/EspruinoTools (`espruino` on NPM, and a straight port of Web IDE internals)
