### ISSUE TITLE
ERROR: Out of Memory!

### ISSUE THREAD

**Issue by msol2004** [espruino/EspruinoDocs#290]
Dear Pals, please help. I have problem with flashing JS code in ESP-12F (4MB version) from proprietary server.

Example below is flashed without problem:
   _SPI1.setup( {sck:D14,mosi:D13,miso:D12,mode:1,order:"msb",baud:1000000} );
   var sx=require( 'SX127x' ).connect({spi:SPI1, cs:D15});_

1) I have tried to flash ESP-12F with JS-code as below:
   _SPI1.setup( {sck:D14,mosi:D13,miso:D12,mode:1,order:"msb",baud:1000000} );
   var addr="http://www.espruino.com/modules/SX127x.js"; // try 0 - espruino web
//   var addr='http://192.169.0.104/SX127x.js';     // try.1 - my RPI with web server
//   var addr='http://192.169.0.104/SX127x';     // try.2 - Raspberry PI
//   var addr='http://lora.ntgel.ru:8128/modules/SX127x.js';    // try.3 - web server
//   var addr='d:/modules/SX127x.js';    // try.4 - local drive
   var sx=require( addr ).connect({spi:SPI1, cs:D15});_

all time the console of ESPRUINO WEB IDE returns message:
   **ERROR: Out of Memory!**

2) I tried to play around options in "Settings / Communications / Module URL", store JS-file on local hard drive, change file name and change compression settings. No positive result, i.e. the message **ERROR: Out of Memory!** is displayed all the time.

3) I tried to put entire **SX127x.js** code in my NodeMCU project and flash ESP-12F. The message **ERROR: Out of Memory!** is displayed again.

The reason of my doings - I have modified SX127x.js according to description of **NiceRF LoRa1276** module. I have already tested it with my Raspberry PI + NiceRF. Now, I am trying to run ESP-12F with NiceFM, and got the problem....

Please guide me - why SX127x.js cannot be flashed from proprietary location? Thank you!

Michael Sol.

**Comment by gfwilliams** [comment]
Closing - if you still have problems, ask on the ESP8266 section of the forum: http://forum.espruino.com/microcosms/925/
