### ISSUE TITLE
tutorials/Web IDE.md

### ISSUE THREAD

**Issue by yerpj** [espruino/EspruinoDocs#301]
Hi ! 
I am just trying to connect to my Puck-js with the native (win64) Espruino web IDE app. 
Among the Bluetooth device driver configuration (Zadig), some lines seem to have been deleted after `Now when you run the Web IDE you should get a` under section `For Windows earlier than 8.1`

**Comment by gfwilliams** [comment]
Thanks - i'll update the website on Monday. It wasn't missing anything important - once you run zadig and restart the IDE it should start working
