### ISSUE TITLE
Use HTTPS for embedded video

### ISSUE THREAD

**Issue by gfwilliams** [espruino/EspruinoDocs#320]
As originally described by @jjok here: https://github.com/espruino/EspruinoDocs/pull/319

Looks like chrome won't display HTTP iframes on an HTTPS site. We need to change the script so it recognises https videos, but also so it automatically makes the link HTTPS

**Comment by jjok** [comment]
Actually, I think any browser would would block/warn you about non-HTTPS content on an HTTPS page.

**Comment by gfwilliams** [comment]
It's probably because I only added HTTPS at about the same time the Puck.js devices shipped, so only noticed it then
