### ISSUE TITLE
Module BME280 and BMP280

### ISSUE THREAD

**Issue by MaBecker** [espruino/EspruinoDocs#325]
Hi @gfwilliams,

Module BME280 (T,P,H) can also be used for BMP280 (T,P)

Options:

* create a new module for BMP280  as a stip down of BME280   <- my  choice

* or extend BME280 to use one module for both sensors  and rename it to BMX280

What do you think ?

**Comment by gfwilliams** [comment]
Looking at it, I guess maybe do a new one. As much as I hate duplication, there's quite a bit of memory used in there for humidity that could be freed if you didn't need it

**Comment by MaBecker** [comment]
add with PR #326
