### ISSUE TITLE
modules/pronto.md

### ISSUE THREAD

**Issue by FredrikWendt** [espruino/EspruinoDocs#358]
This page uses `require("pronto")` but doesn't say where that module can be downloaded from. A standard `npm install pronto` gets me some HTTP server.

**Comment by wilberforce** [comment]
Put this on the right of the ide and upload to the espruino, The module will get downloaded and sent to the espruino

**Comment by FredrikWendt** [comment]
I found out that the Espruino Web IDE will download whatever it gets from http://www.espruino.com/modules/pronto.js and inject that into the code uploaded to your device.
