### ISSUE TITLE
Minor documentation error on Puck.js page

### ISSUE THREAD

**Issue by yerpj** [espruino/EspruinoDocs#372]
in [About Bluetooth LE.md](https://github.com/espruino/EspruinoDocs/blob/master/puck/About%20Bluetooth%20LE.md), it is written 
>If you want to light an LED on a Puck, you can just connect and write LED.set() 
>and a newline to the TX characteristic [...]

I just tried and it appears that one has to write in `RX`characteristic, not in `TX`.

**Comment by gfwilliams** [comment]
Thanks!
