### ISSUE TITLE
Add module AT24 to list of existing modules

### ISSUE THREAD

**Issue by MaBecker** [espruino/EspruinoDocs#407]
No entry for AT24

**Comment by gfwilliams** [comment]
http://www.espruino.com/Modules

> I2C EEPROMs (like AT24C256)

Or do you mean something else?

**Comment by gfwilliams** [comment]
Perhaps we could reword the title: "AT24C256 I2C EEPROMs (and similar)"

**Comment by MaBecker** [comment]
Ups  - there it is. Rewording is a good idea.
