### ISSUE TITLE
EspruinoWifi Add support for setting IP in AP mode

### ISSUE THREAD

**Issue by mrwhy-orig** [espruino/EspruinoDocs#409]
As the WIFI module offers the possibillity to set the APs IP it should be possible with the EspruinoWIFI module as well.

**Comment by gfwilliams** [comment]
> As the WIFI module offers the possibillity to set the APs IP it should be possible with the EspruinoWIFI 

It doesn't really work like that - it's whether it is supported by the AT command library. 

It seems that it can be done with the `AT_CIPAP` command though - http://www.espressif.com/sites/default/files/documentation/4a-esp8266_at_instruction_set_en.pdf

So it wouldn't be too bad to add to https://github.com/espruino/EspruinoDocs/blob/master/devices/EspruinoWiFi.js - and it'd make sense to allow the IP to be set for non-AP mode as well.
