### ISSUE TITLE
puck/Puck.js Controlling Other Pucks.md

### ISSUE THREAD

**Issue by Beaneu** [espruino/EspruinoDocs#413]
Hi. Not a big issue really, but can be puzzling for beginners (like me), since most people will just copy-paste it and expect it to work. In the "Making it faster" code example it's missing this:

// Call this function when the button is pressed
setWatch(sendToggle, BTN, { edge:"rising", debounce:50, repeat: true });

**Comment by gfwilliams** [comment]
Thanks! I've just added that - it should show up in a day or so when I next push changes to the site
