### ISSUE TITLE
Enhance FlashEEPROM to use readMem()  on EPSs

### ISSUE THREAD

**Issue by MaBecker** [espruino/EspruinoDocs#419]
Missing baseMem in  `return E.memoryArea(lastAddr+4, l);`

Will post PR soon for FlashEEPROM.js and FlashEEPROM.js

**Comment by gfwilliams** [comment]
I don't want to put ESP8266 specific hacks in this module.We should really add them in `E.memoryArea` I guess (https://github.com/espruino/Espruino/blob/master/src/jswrap_espruino.c#L864).

I was pretty sure we already had some kind of ESP8266 hack (apart from the byte read stuff) in `peek`, but I can't see it now. Perhaps it was in jshFlashRead

**Comment by MaBecker** [comment]
Thanks for this clear statement.

So there will be a pr for E.memoryArea.
