### ISSUE TITLE
http://www.espruino.com/Puck.js+Eddystone needs an update

### ISSUE THREAD

**Issue by UDXS** [espruino/EspruinoDocs#426]
Recently, Google started to "phase out" goo.gl. This needs to be fixed on the eddystone page.

http://www.espruino.com/Puck.js+Eddystone

**Comment by gfwilliams** [comment]
Thanks. God knows why I base anything on Google products any more :(

**Comment by gfwilliams** [comment]
What's a sensible URL shortener to use instead now? bit.ly? I believe some other tutorials use it as well.

**Comment by UDXS** [comment]
It is fairly popular. They even have a page for former goo.gl users.

**Comment by MaBecker** [comment]
What about setting up a own url shortener like with https://shlink.io/

**Comment by UDXS** [comment]
This isn't exactly a URL shortener meant for our (in the context of the Espruino site) own links. It's really meant more as an example shortener for users.
