### ISSUE TITLE
update boards table for ESP chips

### ISSUE THREAD

**Issue by SpenceKonde** [espruino/EspruinoDocs#447]
http://www.espruino.com/Other+Boards

ESP8266 has 1600 jsvars, not 1023, and costs $2-3, not 10 pounds, and runs at 160mhz not 80. And doesn't it have flash fs too? 

ESP32 has... a different number of jsvars than shown in the table (I don't know what the latest versions have for jsvars currently), and costs $3-7, not $10. 

I might also suggest that the "bat" column for those two be changed to something other than yes or no, because there are some ESP-based boards that do have support for a battery.

**Comment by gfwilliams** [comment]
Pull request?

With the pricing, I'd give the price for a board with USB, not a bare module.

I don't think ESP8266 has FlashFS though.

As you say with 'Bat', maybe remove it and just add it to the 'other' column, as some boards have connectors, some don't, some actually have a battery...

**Comment by wilberforce** [comment]
> ESP8266 - 160mhz not 80. 

It CAN run at 80 - it is a setting

> And doesn't it have flash fs too?

No. It takes up 4Kb of RAM for the buffer. So jsvars have to be knocked back too much

> ESP32 has... a different number of jsvars than shown in the table (I don't know what the latest versions have for jsvars currently),

It's variable - depending if you have BLE turn on or off.

**Comment by wilberforce** [comment]
https://github.com/espruino/EspruinoDocs/blob/master/boards/Other%20Boards.md

**Comment by SpenceKonde** [comment]
Hm, not sure how to describe the number of JSVars on ESP32 on the table...

**Comment by gfwilliams** [comment]
You might as well have two lines (separate them with `<br>`) - one for BLE, one not.

I though ESP8266 *defaulted* to 80Mhz, even if it could do 160. Or maybe the default got changed at some point...

**Comment by wilberforce** [comment]
BLE off:

```
>process.memory();
={ free: 4362, usage: 38, total: 4400, history: 13,
  gc: 0, gctime: 4.367 }
```

BLE On;
`ESP32.enableBLE(1);`

```
>process.memory();
={ free: 2546, usage: 54, total: 2600, history: 0,
  gc: 0, gctime: 2.649 }
```

When we have PSRAM support and the hardware supports  - there will be masses of RAM!
