### ISSUE TITLE
tutorials/Quick Start BLE.md

### ISSUE THREAD

**Issue by claresudbery** [espruino/EspruinoDocs#461]
At the top of this tutorial it says "To make sure the button works correctly you need to put the battery side facing down, with the silver shield facing towards the 'shelf' in the case." But it is not at all clear which bit is the silver shield? If you mean the silver cover that holds the battery in place, it is circular and central so I don't know what you mean by "facing"?

**Comment by gfwilliams** [comment]
Ahh, ok - I think a picture's probably the most helpful here:

http://www.espruino.com/press/puckjs/parts_side.jpg

So everything goes together in the orientation shown there - one on top of the other.

I guess the text could more helpfully refer to the 'Puck.js/www.puck-js.com' text on the PCB being placed against the shelf?
