### ISSUE TITLE
extend SH1106 / SSD1303 to allow delta updates

### ISSUE THREAD

**Issue by MaBecker** [espruino/EspruinoDocs#472]
Like to extend device SH1106 to allow delta updates, because sometime a full update is a  bad choice.

* use function Graphics.getModified(reset) be used to identify the byte that changed 

* or scan buffer after each change

* add something like [  _updateDirtyBytes](https://github.com/noopkat/oled-js/blob/master/oled.js#L518-L567) form  Suz Hinton alias noopkat   oled-js

Than use g.flip() to update full screen or g.glip(1) for delta updates

**Any hints or recommendations?**

**Comment by MaBecker** [comment]
Module SSD1303 use the same way for complete screen updates.

http://www.espruino.com/modules/SSD1306.js

**Comment by gfwilliams** [comment]
Closing this for now - don't see much interest and I think given the relatively small buffers it's work just keeping it simple and pushing everything.
