### ISSUE TITLE
Rename Puck* tutorials to BLE*

### ISSUE THREAD

**Issue by gfwilliams** [espruino/EspruinoDocs#493]
It's confusing when increasingly people aren't just using Puck.js.

Need to have a better way of stopping 404s when this happens - so probably leave `Puck*` in place and add `[MOVED](new_url)` - and make `build.sh` aware that it:

* Should add placeholders for the old files that automatically redirect to the new ones
* Shouldn't link to the old files
* Shouldn't use them in keywords.js
* Should error on any page that links to the old files

There are a few existing pages that do redirects already, but it's far from ideal - and given the amount of pages being moved it's worth doing properly.

**Comment by wilberforce** [comment]
if you keep the same basic paths for the URLs ie. Puck-> BLE you should be able to a single mod_rewrite rule.

Then if an old page his it it automatically redirects to the new page
