### ISSUE TITLE
boards/Smartibot.md

### ISSUE THREAD

**Issue by gomako** [espruino/EspruinoDocs#495]
Smartibot LEDs are `BRG` not `RGB` as in example. [https://www.espruino.com/Smartibot#leds](https://www.espruino.com/Smartibot#leds)

**Comment by gfwilliams** [comment]
Thanks - I'm looking into this. Not sure whether to change the docs or modify the function at the moment.

**Comment by gfwilliams** [comment]
This was actually fixed with 0596e4a7d22401f2d0ca9f3d936c9b1b1e1c21c3
