### ISSUE TITLE
info/Interfacing.md

### ISSUE THREAD

**Issue by hanielsen** [espruino/EspruinoDocs#541]
Very useful examples.
In Python Bleak example, ..._RX and ..._TX
in the run() should be reverted.

**Comment by gfwilliams** [comment]
Just to be sure, what device are you using it with? An Espruino? Some stuff (I can't remember what now - maybe some micro:bit stuff?) actually implemented it backwards.

**Comment by hanielsen** [comment]
It is a micro:bit.
So I learned that.
Thanks
