### ISSUE TITLE
Reference#Graphics Graphics.flip() function is missing from docs

### ISSUE THREAD

**Issue by nikmartin** [espruino/EspruinoDocs#545]
Cant actually find the API reference markdown docs anywhere, or I'd file a more specific issue, but the Graphics API reference is missing the flip() function

**Comment by gfwilliams** [comment]
Thanks for the issue - yes, this is something that's not built into the Graphics instance itself, but it added by graphics drivers (hence the lack of docs). I'll see what I can do to get it in the documentation though
