### ISSUE TITLE
Pixl+multicolour RGB documentation

### ISSUE THREAD

**Issue by bettse** [espruino/EspruinoDocs#555]
https://github.com/espruino/EspruinoDocs/blob/master/boards/Pixl.js%20Multicolour.md#rgb-lighting

`NC.ledTop([])`/`NC.ledBottom([])` didn't turn off the LEDs, I had to use `[0, 0, 0]`

**Comment by gfwilliams** [comment]
Thanks! Just fixed. It seems `NC.ledTop()` does work to turn the LEDs off - it's just the `[]` that was the issue :)
