### ISSUE TITLE
tutorials/Bangle.js Clock.md

### ISSUE THREAD

**Issue by matjaz** [espruino/EspruinoDocs#557]
New interval should also reset on lcd sleep.

    if (on) {
      secondInterval = setInterval(draw, 1000);
      draw(); // draw immediately
    }

**Comment by gfwilliams** [comment]
thanks - you mean the `secondInterval = ` is needed?

**Comment by matjaz** [comment]
exactly. otherwise, the second and next intervals are not cleared.

**Comment by gfwilliams** [comment]
Thanks for letting me know - that was a pretty bad mistake to have in the example ;)
