### ISSUE TITLE
boards/Puck.js.md - Magnetometer sections mentions E.getBatteryPercentage() - should be Puck.getBatteryPercentage()

### ISSUE THREAD

**Issue by huberv** [espruino/EspruinoDocs#558]
Hi all,
In the Magnetometer section the function E.getBatteryPercentage() is mentions. For a Puck, this should be Puck.getBatteryPercentage().

**Comment by MaBecker** [comment]
Hi, you are welcome to create a pull request :)

**Comment by gfwilliams** [comment]
Just done - thanks!

I'm trying to convince people to use `E.getBattery()` rather than `Puck.getBatteryPercentage()` as it can just be copy/pasted between different devices then. I guess I made a typo when changing the docs :)
