### ISSUE TITLE
Should Saving.md contain a list of all possible boot files?

### ISSUE THREAD

**Issue by MaBecker** [espruino/EspruinoDocs#564]
There are more .boot files available than named in Saving.md

* .boot0/1/2/3 loaded in sequence 0 1 2 3 during boot if available

* .bootrst loaded after reset() 

* .bootcde"  not loaded after reset()

Let me know if there should be mentioned more, so I can create a complete pull request.

**Comment by gfwilliams** [comment]
No, I'm pretty sure that's it. I'm pretty sure those are all mentioned? http://www.espruino.com/Saving#boot-process

**Comment by MaBecker** [comment]
Nice, missed that one.
