### ISSUE TITLE
Add more information about lcd_spi_unbuf

### ISSUE THREAD

**Issue by MaBecker** [espruino/EspruinoDocs#565]
Was thinking about  adding  information about this unbuffered lcd spi driver.

* include class and set buffer size for own firmware builds

* sample module to explain the usage

What do you think?

**Comment by gfwilliams** [comment]
Yes, that sounds like a good idea. Any thoughts about where to put it? We could have a tutorial on the Espruino site that covered creating the custom build, adding a module, then adding a `.boot0` file that set up a `g` variable for graphics ?

**Comment by MaBecker** [comment]
Ok, so I will  add a tutorial for a Espruino board how to do this.
