### ISSUE TITLE
"Data Collection with Espruino" link error

### ISSUE THREAD

**Issue by dhassault** [espruino/EspruinoDocs#567]
Hi,

On the doc page `https://www.espruino.com/Data+Collection` the link `example of logging here` is wrong. 

It should be:
`https://www.espruino.com/Bangle.js+Storage`
Instead of:
`https://www.espruino.com/bangle.js+Storage`
`Bangle` instead of `bangle`.

**Comment by MaBecker** [comment]
Thanks for naming it.

**Comment by gfwilliams** [comment]
Thanks!
