### ISSUE TITLE
info/Features.md

### ISSUE THREAD

**Issue by BananaAcid** [espruino/EspruinoDocs#583]
I think, it might help, to state weather or not `async`/`await` is supported along `Promise` (which seems to be supported).

Also I did not understand, on what requirements new language features are based. E.g. where/who is implementing them and can that project be supported?

**Comment by gfwilliams** [comment]
Hi - that's an ES7 feature, so isn't in the list. It's not implemented I'm afraid. There's been some discussion about this but the way  Espruino is implemented makes it difficult.

There's a wishlist for new features at https://github.com/espruino/Espruino/issues/1302

While in principle anyone can contribute new language features as Espruino is Open Source, the reality is I'm the only one that really does any work on the JS engine. You can support my work here if you want to: http://www.espruino.com/Donate
