### ISSUE TITLE
tutorials/Bangle.js App Loader.md

### ISSUE THREAD

**Issue by qucchia** [espruino/EspruinoDocs#608]
Just wanted to note that now in the repository settings, the Github Pages section now has its dedicated section e.g. at https://github.com/espruino/BangleApps/settings/pages.

To change this, all that needs to be done is to change the bit under Enable Github Pages where it says:
> Scroll down to `Github Pages`

To:

> On the left panel, select `Pages`

**Comment by qucchia** [comment]
Additionally, you now have to click `Save` after selecting the `master` branch.

**Comment by gfwilliams** [comment]
Great, thanks! I'll get those changes in
