### ISSUE TITLE
Bangle 2 - get to number

### ISSUE THREAD

**Issue by TobiasReich** [espruino/EspruinoDocs#634]
I sometimes get errors that state

>   "get to [number]"

When I press the button it increases the number but I can't reach the given number anymore since they are lower.

This all happens without me doing anything (e.g. waking up in the morning, seeing the alarm didn't trigger).

Is this a normal feature of something? How can I find out which app is causing this? And can I prevent it from happening? After all, my watch requires a restart afterwards and no alarms are triggered in the mean time. Software is up to date.

![bangle-error](https://user-images.githubusercontent.com/10375845/156336979-01ba3d73-0b85-4d3b-aeb2-3c761f9648ce.jpg)

**Comment by gfwilliams** [comment]
Please don't file issues on EspruinoDocs for this type of thing. It's really a question for the forum: http://forum.espruino.com/

I just did a search for the text `"Get to"` in apps and it looks like you've installed `Q Alarm` or `Hard Alarm` apps, and turned on the option for the 'hard' alarm. Just uninstall whichever of those apps you have and you'll be fine
