### ISSUE TITLE
tutorials/Bangle.js App Settings.md

### ISSUE THREAD

**Issue by TheLogan** [espruino/EspruinoDocs#652]
eval(require("Storage").read("myapp.settings.js"))(()=>load());

results in the following:
Uncaught Error: Function not found!
...).read("myapp.settings.js"))(()=>load());console.log('started...

I've also attempted to call load() directly, and on my bangle.js 2 it doesn't seem to do anything.

**Comment by gfwilliams** [comment]
What's in `myapp.settings.js`?

Is it that you missed:

> This is great for testing, however to create a settings app, you must remove the (load) from the end of the code, so it should look like this:
