### ISSUE TITLE
Bangle2.js Firmware Source Code and Hardware Schematic

### ISSUE THREAD

**Issue by freetink3r** [espruino/EspruinoDocs#655]

**Comment by gfwilliams** [comment]
Hi - did you find everything you needed in the end?

**Comment by freetink3r** [comment]
Yes! Thanks for following up! I was embarrassed by my original question, so removed the description.

I had some trouble connecting the Bangle.js2 to the nRF52 DK, but figured it out in the end. There's a bug in the current documentation, which references an image file nRF52DK.jpg, but the actual file is named nRF52DK.png. The image also doesn't show the short required between the `VTG` and `VDD` pins, which is necessary on the latest nRF52 DK boards. I created a pull request that addresses both of these issues: https://github.com/espruino/EspruinoDocs/pull/656

**Comment by gfwilliams** [comment]
Great, thanks! Just merged - surprised about the VTG thing though - which board in particular are you using it with?

I took a quick look and have updated some links that I think were wrong, that may give you some more info: https://github.com/espruino/EspruinoDocs/commit/ae2a45f0dc0e1614ace507f5cc75844b4f0e0e28

If you do find anywhere we could link to things better, please let me know (or even better, PRs like your last one are great!).
