### ISSUE TITLE
Data Streaming To GCP

### ISSUE THREAD

**Issue by jaredfiacco2** [espruino/EspruinoDocs#666]
I made a tutorial for getting data from your puck.js into Google Cloud Platform's Pub/Sub & storing it in Bigquery for visualization in Data Studio. I've had this running for the past few days at home and it's working well! 
The ingestion process is outlined in the picture below:
![process-map](https://user-images.githubusercontent.com/57553108/188284962-24029fc8-24e6-4f6d-8502-3c79578d967a.png)

The code uses the "bleeverything" app:
https://github.com/espruino/EspruinoApps/pull/4

I'll submit a Pull Request for it soon!

**Comment by gfwilliams** [comment]
This looks great - and thanks for the pics too!

Just so you know, there's no real need to file an issue too if you don't want to - just the PR itself will do, and you can add explanation and stuff there is needed.

It's now all merged but the website gets updated manually, so it may take a few days to appear 'live'
