### ISSUE TITLE
info/Font Converter.md

### ISSUE THREAD

**Issue by Shimmy337** [espruino/EspruinoDocs#688]
Hi there, I've been experiencing an issue with the font converter.
It seems like the fonts are oversized regardless of which font I use from Google.
Hope the image below helps!
![image](https://user-images.githubusercontent.com/18481514/219842882-067399b8-ddce-4e64-9b56-fc5198973813.png)

**Comment by Shimmy337** [comment]
Apologies, just tried it on Edge Browser and it works fine. It's just Brave browser that I had issues with.

**Comment by gfwilliams** [comment]
Thanks - that's a strange one though - I wonder why it fails, as it should use the same rendering engine as Edge.

Even Firefox works ok which uses something different. The main text on the screenshot looks small though - do you have some custom zoom level set up? Maybe it would work if viewed at 100%? It still works ok for me with zoom in chrome, but maybe Brave does something different.

**Comment by Shimmy337** [comment]
Hey again! Thanks for getting back to me.
Made sure my zoom was set to default and still not happy regardless of the zoom.
![image](https://user-images.githubusercontent.com/18481514/221332787-76467574-c59b-4ed3-a9c1-bb8f48134ae5.png)

No fuss though, I'm fine to just use another browser to get the fonts.
Thanks for the help! :)
