### ISSUE TITLE
Add "Bangle.js Battery Load/Intensity notes"

### ISSUE THREAD

**Issue by thyttan** [espruino/EspruinoDocs#702]
On the forum some knowledge of what contributes to faster battery drain has surfaced. I think it could be helpful to compile these in a page maybe similar to the [Espruino Performance Notes](http://www.espruino.com/Performance). Or maybe it should live in the Bangle.js wiki?

If I get around to compiling such a page I'll search the forum first and also start a forum thread asking for the members input.

Please comment below with e.g. tips to add to the page.

**Comment by thyttan** [comment]
There is a section in the wiki, maybe just add to that if I find something that's missing.

**Comment by gfwilliams** [comment]
Good idea - there is a mention of things that draw power on http://www.espruino.com/Bangle.js2#power-consumption but maybe we could also point to the wiki from there, or elaborate a little?
