### ISSUE TITLE
Forum isn't redirecting correctly 

### ISSUE THREAD

**Issue by mariusGundersen** [espruino/EspruinoDocs#704]
It looks like the forums aren't redirecting properly:

![Screenshot_20231208_095511_Firefox Beta](https://github.com/espruino/EspruinoDocs/assets/464152/da4b6129-f310-4709-9a1a-a2475aa3876c)

**Comment by gfwilliams** [comment]
Ok, I think it's solved now - the forum provider moved hosting providers and screwed things up a bit, but I think I've managed to fix it now
