### ISSUE TITLE
tutorials/Software PWM.md

### ISSUE THREAD

**Issue by IntellijouleIncorp** [espruino/EspruinoDocs#711]
What is the maximum repetition rate for the PWM output?  A 100KHZ to 1 MHZ output range for the PWM would make the puck.js2 more valuable.

**Comment by gfwilliams** [comment]
Using hardware PWM on Puck.js the counter frequency is 16Mhz, and you can get a max frequency of 4Mhz (but only with a 2 bit resolution). So for example this works fine:

```
analogWrite(D1,0.5,{freq:4000000})
```

I'll update the `analogWrite` docs.
